# Generated by Django 5.2.1 on 2025-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('year_of_study', models.IntegerField()),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
    ]
