# Generated by Django 5.2.1 on 2025-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.TextField(db_column='Building_ID', primary_key=True, serialize=False)),
                ('address', models.TextField(db_column='Address')),
            ],
            options={
                'db_table': 'Building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(db_column='Class_ID', primary_key=True, serialize=False)),
                ('start_time', models.TextField(db_column='Start_Time')),
                ('end_time', models.TextField(db_column='End_Time')),
                ('max_capacity', models.IntegerField(db_column='Max_Capacity')),
                ('enrolled_count', models.IntegerField(db_column='Enrolled_Count')),
                ('is_cancelled', models.IntegerField(blank=True, db_column='Is_Cancelled', null=True)),
                ('waiting_list_count', models.IntegerField(blank=True, db_column='Waiting_List_Count', null=True)),
            ],
            options={
                'db_table': 'Class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.AutoField(db_column='Lecturer_ID', primary_key=True, serialize=False)),
                ('first_name', models.TextField(db_column='First_Name')),
                ('last_name', models.TextField(db_column='Last_Name')),
                ('email', models.TextField(db_column='Email')),
            ],
            options={
                'db_table': 'Lecturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.TextField(db_column='Reservation_Date')),
                ('note', models.TextField(db_column='Note')),
            ],
            options={
                'db_table': 'Reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('status_id', models.AutoField(db_column='Status_ID', primary_key=True, serialize=False)),
                ('status_name', models.TextField(db_column='Status_Name')),
            ],
            options={
                'db_table': 'Reservation_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='Room_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(db_column='Subject_ID', primary_key=True, serialize=False)),
                ('subject_name', models.TextField(db_column='Subject_Name')),
            ],
            options={
                'db_table': 'Subject',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
