# Generated by Django 5.2.1 on 2025-05-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_building_class_lecturer_reservation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
