# Generated by Django 5.2.1 on 2025-05-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
    ]
