# Generated by Django 5.2.1 on 2025-05-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': False},
        ),
    ]
