# Generated by Django 5.2.1 on 2025-05-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
    ]
