# Generated by Django 5.2.1 on 2025-05-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
