# Generated by Django 5.2.1 on 2025-05-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_building_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(db_column='Address', unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.TextField(blank=True, db_column='Building_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='building',
            table=None,
        ),
    ]
