# Generated by Django 5.2.1 on 2025-05-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_building_address_alter_building_building_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
