# Generated by Django 5.2.1 on 2025-05-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_building_options_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
    ]
