# Generated by Django 5.2.1 on 2025-05-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_building_options_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
