# Generated by Django 5.2.1 on 2025-05-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='Building',
        ),
    ]
