# Generated by Django 5.2.1 on 2025-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_building_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(db_column='Address'),
        ),
        migrations.AlterModelTable(
            name='building',
            table=None,
        ),
    ]
