# Generated by Django 5.2.1 on 2025-05-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_building_address_alter_building_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
