# Generated by Django 5.2.1 on 2025-05-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
