# Generated by Django 5.2.1 on 2025-06-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
