# Generated by Django 5.2.1 on 2025-06-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
    ]
