# Generated by Django 5.2.1 on 2025-06-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_class_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'managed': False},
        ),
    ]
