# Generated by Django 5.2.1 on 2025-06-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_class_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
    ]
