# Generated by Django 5.2.1 on 2025-06-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_class_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.class')),
            ],
            options={
                'unique_together': {('class_field', 'training_date')},
            },
        ),
    ]
